### ISSUE TITLE
[v15.0.0 regression] Google set incorrectly displays 🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland flag as 🇸🇨 Seychelles flag

### ISSUE THREAD

**Issue by andersk** [iamcal/emoji-data#231]
As of commit d5c6684a5573c26432f4bbd5a84645c7b477ef65 (#223) in v15.0.0, the Google set incorrectly displays 🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland flag (1f3f4-e0067-e0062-e0073-e0063-e0074-e007f) as if it were 🇸🇨 Seychelles flag:

✔️ v14.0.0, img-google-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v14.0.0/img-google-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v14.0.0/img-google-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
✔️ v14.0.0, img-google-136 [![](https://raw.githubusercontent.com/iamcal/emoji-data/v14.0.0/img-google-136/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v14.0.0/img-google-136/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
❌ v15.0.0, img-google-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-google-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-google-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
❌ v15.0.0, img-google-136: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-google-136/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-google-136/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)

All sets other than Google are unaffected:

✔️ v15.0.0, img-apple-160: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-apple-160/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-apple-160/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
✔️ v15.0.0, img-apple-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-apple-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-apple-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
✔️ v15.0.0, img-facebook-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-facebook-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-facebook-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
✔️ v15.0.0, img-facebook-96: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-facebook-96/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-facebook-96/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
✔️ v15.0.0, img-twitter-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-twitter-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-twitter-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
✔️ v15.0.0, img-twitter-72: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-twitter-72/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-twitter-72/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)

The [upstream image](https://github.com/googlefonts/noto-emoji/blob/v2.038/third_party/region-flags/waved-svg/emoji_u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f.svg) in Noto Emoji is unaffected:

[![](https://raw.githubusercontent.com/googlefonts/noto-emoji/v2.038/third_party/region-flags/waved-svg/emoji_u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f.svg)](https://github.com/googlefonts/noto-emoji/blob/v2.038/third_party/region-flags/waved-svg/emoji_u1f3f4_e0067_e0062_e0073_e0063_e0074_e007f.svg)

The related 🏴󠁧󠁢󠁥󠁮󠁧󠁿 England flag (1f3f4-e0067-e0062-e0065-e006e-e0067-e007f) and 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales flag (1f3f4-e0067-e0062-e0077-e006c-e0073-e007f) are unaffected:

✔️ v15.0.0, img-google-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-google-64/1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-google-64/1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.png)
✔️ v15.0.0, img-google-136: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-google-136/1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-google-136/1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.png)
✔️ v15.0.0, img-google-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-google-64/1f3f4-e0067-e0062-e0077-e006c-e0073-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-google-64/1f3f4-e0067-e0062-e0077-e006c-e0073-e007f.png)
✔️ v15.0.0, img-google-136: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.0/img-google-136/1f3f4-e0067-e0062-e0077-e006c-e0073-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.0/img-google-136/1f3f4-e0067-e0062-e0077-e006c-e0073-e007f.png)

**Comment by EtienneLem** [comment]
**black_bird** is missing for the Google images and it breaks all the emojis listed after it. According to the JSON, it should be at **[11, 25]** on the sheet.

### Data
```json
{
  "name": "BLACK BIRD",
  "unified": "1F426-200D-2B1B",
  "non_qualified": null,
  "docomo": null,
  "au": null,
  "softbank": null,
  "google": null,
  "image": "1f426-200d-2b1b.png",
  "sheet_x": 11,
  "sheet_y": 25,
  "short_name": "black_bird",
  "short_names": [
      "black_bird"
  ],
  "text": null,
  "texts": null,
  "category": "Animals & Nature",
  "subcategory": "animal-bird",
  "sort_order": 620,
  "added_in": "15.0",
  "has_img_apple": true,
  "has_img_google": true,
  "has_img_twitter": false,
  "has_img_facebook": false
},
```

But if we compare the Apple vs. Google sheets, we can see the black bird is missing on Google:

### Apple
<img width="552" alt="apple" src="https://github.com/iamcal/emoji-data/assets/436043/ad7cffad-90a4-4ed8-86e3-5b624dac1a18">

> https://cdn.jsdelivr.net/npm/emoji-datasource-apple@15.0.0/img/apple/sheets-256/64.png

### Google
<img width="512" alt="google" src="https://github.com/iamcal/emoji-data/assets/436043/d0745714-3749-4ef9-acd9-5f1a03d8c4fd">

> https://cdn.jsdelivr.net/npm/emoji-datasource-google@15.0.0/img/google/sheets-256/64.png

**Comment by EtienneLem** [comment]
Ah wait, sorry, it was fixed in **v15.0.1**; make sure you use the latest version.

**Comment by andersk** [comment]
I am using the latest version—I just reported it for the version in which it regressed. There have been no commits to the images since v15.0.0; my issue was not fixed in v15.0.1.

❌ v15.0.1, img-google-64: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.1/img-google-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.1/img-google-64/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)
❌ v15.0.1, img-google-136: [![](https://raw.githubusercontent.com/iamcal/emoji-data/v15.0.1/img-google-136/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)](https://github.com/iamcal/emoji-data/blob/v15.0.1/img-google-136/1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png)

**Comment by iamcal** [comment]
Thanks for reporting this (and in so much detail). This broken when Google changed how they laid out their repo and specifically the calculated/composed flags. I'm landing a fix now that addresses this.

**Comment by andersk** [comment]
You’re welcome! If you don’t mind my drawing some attention to a separate issue, can you please also take a look at this very easy PR?

- #217

**Comment by iamcal** [comment]
This is now fixed on master. I'll wait a few days before cutting a new release, while other bug reports come in.

**Comment by jwheare** [comment]
Just to let you know that I've now updated IRCCloud emoji to 15.1 and all looks fine. Thanks for your efforts.
